config/routes.rb
Rails.application.routes.draw do
  root 'public_recipes#index'
  devise_for :users, controllers: { registrations: "registrations" }

  resources :recipes, only: %i[index show new create destroy] do
    resources :recipe_foods, only: [:index, :edit, :destroy]
  end
  
  resources :foods, only: [:index, :new, :create, :destroy]

  get 'public_recipes/:id', action: :show, controller: 'public_recipes'

  get 'general_shopping_list', to: 'shopping_list#missing_items'
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    return unless user.present?

    can(:manage, Recipe, user:)
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/food.rb
class Food < ApplicationRecord
  belongs_to :user
  has_many :recipe_foods
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :user
  has_many :recipe_foods

  validates :name, :preparation_time, :cooking_time, :description, presence: true
end

app/models/recipe_food.rb
class RecipeFood < ApplicationRecord
  belongs_to :food
  belongs_to :recipe
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :foods
  has_many :recipes
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  private

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[name])
  end
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  before_action :authenticate_user!
  # GET /foods {food list page}
  def index
    @foods = Food.where(user: current_user)
  end

  # GET /foods/new {create form page}
  def new
    @food = Food.new
  end

  # POST /foods {Create Action}
  def create
    @food = Food.new(food_params)
    if @food.save
      redirect_to foods_path, notice: 'Food was successfully created.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  # Delete Food Action
  def destroy
    @food = Food.where(id: params[:id], user: current_user)
    redirect_to foods_path, notice: 'Food was successfully destroyed.' if @food.destroy(params[:id])
  end

  private

  def food_params
    params.require(:food).permit(:name, :price, :measurement_unit).merge(user: current_user)
  end
end

app/controllers/public_recipes_controller.rb
class PublicRecipesController < ApplicationController
    def index
      @recipes = Recipe.includes(:user).where(public: true)
    end
    def show
      @recipe, = Recipe.where(id: params[:id], public: true)
    end
end

app/controllers/recipe_foods_controller.rb
class RecipeFoodsController < ApplicationController
  include RecipeFoodHelper

  def new
    @recipe_food = RecipeFood.new
    query_recipe
  end

  def create
    query_recipe
    @recipe_food = RecipeFood.new(create_params)
    if @recipe_food.save
      redirect_to(recipe_url(@recipe), notice: 'Ingredient has been added successfully!')
    else
      render(:new, alert: 'Something went wrong!')
    end
  end

  def edit
    query_ingredient
  end

  def update
    query_ingredient

    if @recipe_food.update(update_params)
      flash[:notice] = 'Recipe food updated Successfully!'
    else
      flash[:alert] = 'Something went wrong!'
    end

    redirect_to(recipe_url(@recipe_food.recipe))
  end

  def destroy
    query_ingredient
    @recipe_food.destroy
    redirect_to(recipe_url(params[:recipe_id]), notice: 'Ingredient deleted!')
  end

  private

  def create_params
    params.permit(:quantity, :recipe_id)
  end

  def update_params
    params.require(:ingred).permit(:quantity)
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :authenticate_user!
  def index
    @recipes = Recipe.where(user: current_user).order(created_at: :desc)
  end

  def new
    @recipe = Recipe.new
  end

  def create
    @recipe = Recipe.new(recipe_params)
    if @recipe.save
      redirect_to recipes_path, notice: 'Recipe created successfully!'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @recipe, = Recipe.where(id: params[:id], user: current_user)
    @foods = Food.where(user: current_user)
  end

  def destroy
    @recipe, = Recipe.where(id: params[:id], user: current_user)
    redirect_to recipes_path, notice: 'Recipe deleted!' if @recipe.destroy
  end

  private

  def recipe_params
    params.require(:recipe).permit(:name, :preparation_time, :cooking_time, :description).merge(user: current_user)
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  before_action :authenticate_user!
  protected

  def after_sign_up_path_for(_resource)
    '/'
  end
  def after_sign_in_path_for(_resource)
    '/'
  end
  def after_sign_out_path_for(_resource)
    '/'
  end
end

app/controllers/shopping_list_controller.rb
class ShoppingListController < ApplicationController
  def missing_items
    og = Food.where(user: current_user)
    mr_ids = RecipeFood.where.not('food_id not in (?)', Array.wrap(og.ids)).ids
    found_ids = Set.new(og.ids) - Set.new(mr_ids)

    @counter = og.length
    @price = og.sum(:price)
    @foods = Food.where(id: found_ids)

    render(:index)
  end
end

app/helpers/recipe_foods_helper.rb
module RecipeFoodsHelper
  def query_recipe
    @recipe, = Recipe.where(id: params[:recipe_id], user: current_user)
  end

  def query_ingredient
    @recipe_food, = RecipeFood.where(params.permit(:id, :recipe_id))
  end
end

app/views/foods/index.html.erb
<div class=" m-3 d-flex justify-content-between align-items-center w-75 food-header" >
<h1>Foods</h1>

 <%= link_to 'Add Food',new_food_path, class: "button" %> 

</div>


<table  class="table table-bordered m-5 w-75 food-table">
<thead>
<tr>
<th scope="col">Food </th>
<th>Measurement unit </th>
<th>Unit price </th>
<th>Actions </th>
</tr>
</thead>
<tbody>
    <% @foods.each do |food|%>
<tr>
            <td> <%= food.name%></td>
            <td> <%= food.measurement_unit%></td>
            <td> $ <%= food.price%></td>
            <td><%= button_to 'delete', food_path(food.id), method: :delete, class:"btn btn-warning"%></td>
   </tr>
    <%end%>
</tbody>
 </table>

app/views/foods/new.html.erb
<section class=" d-flex flex-column justify-content-center px-5  w-50 section pt-3" >
  <h1 class="text-center mb-5">New food</h1>

  <%= form_with model: @food do |f|%>

  <div class="mb-3 px-5">
    <%= f.label :name %> <br />
    <%= f.text_field :name, autofocus: true,placeholder: 'Food Name',class:"form-control" %>
  </div>

  <div class="mb-3 px-5">
    <%= f.label :measurement_unit %> <br />
    <%= f.text_field :measurement_unit, placeholder: 'Measurement Unit', class:"form-control" %>
  </div>

  <div class="mb-3 px-5">
    <%= f.label :price %> <br />
    <%= f.text_field :price, placeholder: 'Price', class:"form-control" %>
  </div>

  <div class="mb-3 px-5"><%= f.submit "Add Food", class:"button" %></div>

  <% end %>
  <br />

  <div class="mb-3 px-5"><%= link_to "Back to foods", foods_path %></div>

</section>

app/views/foods/show.html.erb
<p style="color: green"><%= notice %></p>

<div>
  <%= link_to "Edit this food", edit_food_path(@food) %> |
  <%= link_to "Back to foods", foods_path %>

  <%= button_to "Destroy this food", @food, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RecipeApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render partial: "shared/navbar" %>
    <div class="message-container">
      <p class="notice message"><%= notice %></p>
      <p class="alert message"><%= alert %></p>
    </div>
    
    <div class="container d-flex justify-content-center flex-column align-items-center" >
      <%= yield %>
    </div>
  </body>
</html>

app/views/public_recipes/_card.html.erb
<div class="public-recipe-card">
  <h3><%= link_to recipe.name, "/public_recipes/#{recipe.id}"  %></h3>
  <p>By: <%= recipe.user.name %></p>
  <p>Cooking Time: <%= recipe.cooking_time %></p>
  <p>Description: <%= recipe.description %></p>
</div>

app/views/public_recipes/index.html.erb
<section class="public-recipes">
  <h1 class="text-center">Public Recipes</h1>
  <div class="recipes-box">
    <% @recipes.each do |recipe| %> 
    <%= render('card', recipe:) %>
    <% end %>
  </div>
</section>

app/views/public_recipes/show.html.erb
<%= render 'shared/recipe_show', recipe: @recipe %>

app/views/recipes/_card.html.erb
<div>
  <h3>
    <div class="recipe-name">
      <%= link_to(recipe.name, recipe_path(recipe.id)) %>
    </div>
  </h3>
  <div>
    <p><%= recipe.description %></p>
  </div>
</div>
<%= button_to "Delete", recipe_path(recipe.id), method: :delete, class:"btn
btn-warning mb-3" %>

app/views/recipes/index.html.erb
 <h2>RECIPE LIST</h2>

<section class="d-flex flex-column align-items-center recipe-bg ">
  <h1 class="text-center mb-2 pt-5">Recipes</h1>

  <div class="d-flex flex-column link px-5">
    <% if @recipes.empty? %>

      <h2 class="text-center">The list is empty.</h2>
    <% else %>
        <% @recipes.each do |recipe|  %>
        <%= render('card', recipe:) %>
      <% end %>
    <% end %>
  </div>
    <div class="recipe-name with-border px-5 mb-5"> 
        <%= link_to("Add New Recipe", new_recipe_path) %>
    </div>
</section>

app/views/recipes/new.html.erb
<section class=" d-flex flex-column justify-content-center px-5  w-50 section pb-5 pt-3">
  <h1 class="text-center">New Recipe</h1>

  <%= form_with model: @recipe do |f|%>

  <div class="mb-1">
    <%= f.label :name %> <br />
    <%= f.text_field :name, autofocus: true,placeholder: 'Recipe Name', class:"form-control input" %>
  </div>

  <div class="mb-1">
    <%= f.label :preparation_time %> <br />
    <%= f.text_field :preparation_time, placeholder: 'preparation_time' ,class:"form-control input" %>
  </div>

  <div class="mb-1">
    <%= f.label :cooking_time %> <br />
    <%= f.text_field :cooking_time, placeholder: 'cooking_time', class:"form-control input" %>
  </div>

  <div class="mb-1">
    <%= f.label :description %> <br />
    <%= f.text_field :description, placeholder: 'description', class:"form-control" %>
  </div>


  <div class="actions mt-3"><%= f.submit "Add Recipe", class:"button" %></div>

  <% end %>
  <br />

  <div class="link recipe"><%= link_to "Back to Recipes", recipes_path %></div>
</section>

app/views/recipes/show.html.erb
<%= render 'shared/recipe_show', recipe: @recipe %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid navbar-custom">
    <%= link_to "Recipe App", root_path, class: "navbar-brand text-white p-3"%>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
        <%= link_to "Public Recipes", root_path, class: "nav-links mx-3"%>
        </li>
        <% if user_signed_in? %>
        <li class="nav-item">
        <%= link_to "Recipes", recipes_path, class: "nav-links mx-3"%>
        </li>
        <li class="nav-item">
        <%= link_to "Foods", foods_path, class: "nav-links mx-3"%>
        </li>
        <li class="nav-item">
          <%= link_to "Sign out", destroy_user_session_path, data: { turbo_method:
  :delete } %>
        </li>
        <% else %>
        <li class="nav-item">
        <%= link_to "Sign In", new_user_session_path, class: "nav-links mx-3"%>
        </li>
        <li class="nav-item">
        <%= link_to "Sign Up", new_user_registration_path, class: "nav-links mx-3"%>
        </li>
        <% end %>

        
      </ul>
    </div>
  </div>
</nav>

app/views/shared/_recipe_show.html.erb
<section class="container">
  <h1 class="text-center mb-5"><%= recipe.name %></h1>
  <span class="badge badge-primary">Private</span>
  <div class="recipe-info d-flex justify-content-around">
    <div>
      <h5>Preparation time: <%= recipe.preparation_time %></h5>
      <h5>Cooking time: <%= recipe.cooking_time %></h5>
      <div>
        <h3 class="mt-5">Description</h3>
        <p><%= recipe.description %></p>
      </div>
    </div>
    <div class="recipe-stat">
      <% if recipe.public %>
      <span class="btn btn-warning">Public</span>
      <% else %>
      <span class="btn btn-primary">Private</span>
      <% end %>
    </div>
  </div>
  <div class="mt-5 d-flex justify-content-around">
    <button
      type="button"
      class="btn btn-primary"
      data-bs-toggle="modal"
      data-bs-target="#recipeModal"
    >
      <%= link_to "Generate shopping list", general_shopping_list_path %>
    </button>
    <% if can?(:update, recipe) %> <%= link_to "Add ingredient", foods_path,
    class: "btn btn-danger" %> <% end %>
  </div>
  <table class="table table-bordered m-5 w-75 food-table">
    <thead>
      <tr>
        <th scope="col">Food</th>
        <th>Measurement unit</th>
        <th>Unit price</th>
        <th>Actions</th>
      </tr>
    </thead>
    <tbody>
      <% if @foods.nil? %>
      <h3>the list is empty</h3>
      <% else %> <% @foods.each do |food|%>
      <tr>
        <td><%= food.name%></td>
        <td><%= food.measurement_unit%></td>
        <td>$ <%= food.price%></td>
        <td>
          <%= button_to 'delete', food_path(food.id), method: :delete,
          class:"btn btn-warning"%>
        </td>
      </tr>
      <%end%>
    </tbody>
    <% end %>
  </table>
</section>

app/views/shopping_list/index.html.erb
<div class="container-fluid w-50 d-flex flex-column align-items-center">
  <h1>Shopping list</h1>
  <div class="container-fluid w-100 d-flex justify-content-between align-items-center my-4">
    <div class="container-fluid w-50 d-flex flex-column align-items-center">
      <p>Total Food Items: <%= @counter %></p>
      <p>Total price of missing food: $<%= @price %></p>
    </div>

  <% unless @foods.empty? %>
    <table class="table table-bordered table-striped">
      <thead>
        <tr>
          <th scope="col">Food</th>
          <th scope="col">Quantity</th>
          <th scope="col">Price</th>
        </tr>
      </thead>
    <tbody>
        <% @foods.each do |item| %>
          <tr>
            <td><%= item[:name] %></td>
            <td><%= item[:quantity] %> <%= item[:measurement_unit] %> </td>
            <td>$<%= item[:price] %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  <% else %>
    <h2> No missing food items</h2>
  <% end %>
</div>